Repository Udemy-Uandmy/Uandmy_Frontend, pull requests merged in 2024-09, with the labels that each got.

#22 [✨feat]: 온보딩 스플래쉬 페이지 UI 구현
  public/images/splash-icon-bg.png
  public/images/splash-icon.png
  src/app/globals.css
  src/app/layout.tsx
  src/app/splash/page.tsx
  src/app/walkthrough/page.tsx
  tailwind.config.ts
Labels: FEAT

#41 [✨feat]: 스터디 탐색하기(search) 페이지 구현
  public/images/DropdownIcon.svg
  public/images/Filter.svg
  public/images/MagnifyingGlass.svg
  src/app/manage-studyroom/page.tsx
  src/app/mypage/page.tsx
  src/app/search/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Gnb.tsx
  src/components/common/ToggleSwitch.tsx
Labels: FEAT

#55 [🔨chore]: supabase + prisma 개발 환경 세팅
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20240902082857_init/migration.sql
  prisma/migrations/20240902085315_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/api/index.tsx
  src/app/api/auth/signin/route.ts
  src/app/api/auth/signup/route.ts
  src/app/testlogin/page.tsx
  src/app/testsignup/page.tsx
  src/lib/prisma.ts
  src/utils/supabaseClient.ts
Labels: CHORE

#64 [✨feat]: 셀렉트 박스 바텀시트 컴포넌트
  src/components/common/JobSelect.tsx
Labels: FEAT

#45 [✨feat]: 온보딩 페이지 구현
  package-lock.json
  package.json
  public/images/ClappingHands.svg
  public/images/Designer.svg
  public/images/Developer.svg
  public/images/Planner.svg
  src/app/login/page.tsx
  src/app/onboarding/page.tsx
  src/components/common/CheckBox.tsx
  src/components/common/CheckBoxList.tsx
  src/components/common/UserProfileCard.tsx
  src/components/onboarding/Characters.tsx
  src/components/onboarding/JobCard.tsx
  src/components/onboarding/SelectedJob.tsx
  src/components/onboarding/StepCompleted.tsx
  src/components/onboarding/StudyPeriod.tsx
  src/components/onboarding/StudyPurpose.tsx
Labels: FEAT

#67 [✨feat]: CountInput 컴포넌트
  src/components/common/CountInput.tsx
Labels: FEAT

#70 [✨feat]: 스터디 생성 페이지 구현
  package-lock.json
  src/app/createstudy/page.tsx
  src/app/login/page.tsx
  src/components/common/CountInput.tsx
  src/components/common/Input.tsx
  src/components/common/JobSelect.tsx
  src/components/common/MultiSelect.tsx
  tailwind.config.ts
Labels: FEAT

#69 [✨feat]: 대기중인 요청 페이지, 공개용 프로필 페이지 구현
  src/app/login/page.tsx
  src/app/pending-request/page.tsx
  src/app/public-profile/[id]/page.tsx
  src/app/public-profile/page.tsx
  src/components/common/Button.tsx
  src/components/common/PendingProfileCard.tsx
  src/components/common/StudyExperienceCard.tsx
  src/components/common/Tag.tsx
  src/components/common/TagList.tsx
Labels: FEAT

#59 [✨feat]: 스터디룸 생성 완료 페이지 퍼블리싱
  public/images/clapping-hands.svg
  public/images/figma-icon.svg
  src/app/studyroomcreated/page.tsx
  src/components/common/StudyCreateCard.tsx
Labels: FEAT

#73 [✨feat]: 로그인/회원가입 api 구현
  package-lock.json
  package.json
  prisma/migrations/20240904135156_init/migration.sql
  prisma/schema.prisma
  src/app/api/auth/signin/route.ts
  src/app/api/auth/signup/route.ts
  src/app/api/user/profile/route.ts
  src/app/testsignup/page.tsx
Labels: FEAT

#75 [✨feat]: 마이페이지 구현
  public/images/Alarm.svg
  public/images/Before.svg
  public/images/Bookmark.svg
  public/images/Bookmark2.svg
  public/images/Checking.svg
  public/images/Join.svg
  public/images/Joining.svg
  public/images/Navigate.svg
  public/images/Waiting.svg
  src/app/mypage/page.tsx
  src/components/common/UserStatusSummary.tsx
Labels: FEAT

#74 [🎨style] 스터디룸 생성 페이지 디자인 수정, 셀렉트 컴포넌트 모달 형식으로 변경
  src/app/createstudy/page.tsx
  src/components/common/MultiSelect.tsx
Labels: STYLE

#78 [✨feat]: 로딩 스피너 컴포넌트 구현
  public/images/loading-spinner.svg
  src/components/common/LoadingSpinner.tsx
Labels: FEAT

#79 [✨feat]: 확인 모달 컴포넌트
  src/components/common/ConfirmModal.tsx
Labels: FEAT

#80 [✨feat]: 하단 버튼 컴포넌트 구현
  package-lock.json
  src/app/login/page.tsx
  src/app/pending-request/page.tsx
  src/app/postdetail/page.tsx
  src/app/public-profile/[id]/page.tsx
  src/app/signup/page.tsx
  src/components/common/BottomButton.tsx
  src/components/common/Button.tsx
Labels: FEAT

#85 [✨feat]: 스터디룸 관리 - 신청자 관리, 내 신청 내역 구현
  public/images/AccordionDown.svg
  public/images/AccordionUp.svg
  public/images/Close.svg
  src/app/manage-studyroom/page.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/PendingProfileCard.tsx
Labels: FEAT

#88 [✨feat]: 페이지 연결 및 로딩 컴포넌트 적용
  src/app/createstudy/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/manage-studyroom/page.tsx
  src/app/mypage/page.tsx
  src/app/pending-request/page.tsx
  src/app/postdetail/page.tsx
  src/app/public-profile/[id]/page.tsx
  src/app/search/page.tsx
  src/app/signup/page.tsx
  src/app/studyroom/page.tsx
  src/app/studyroomcreated/page.tsx
  src/components/common/BottomButton.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/common/ProgressBar.tsx
  src/components/onboarding/Characters.tsx
  src/components/onboarding/SelectedJob.tsx
  src/components/onboarding/StepCompleted.tsx
  src/components/onboarding/StudyPeriod.tsx
  src/components/onboarding/StudyPurpose.tsx
Labels: FEAT, STYLE

#91 [✨feat]: 상단바 구현
  src/app/createstudy/page.tsx
  src/app/pending-request/page.tsx
  src/app/postdetail/page.tsx
  src/app/public-profile/[id]/page.tsx
  src/components/common/NavHeader.tsx
Labels: FEAT

#93 [✨feat]: signin api 연결
  src/app/api/auth/signin/route.ts
  src/app/api/auth/signin/route.tsx
  src/app/splash/page.tsx
  src/app/testlogin/page.tsx
  src/middleware.ts
Labels: FEAT

#97 [♻️refactor]: 로그인, 회원가입 경로 수정
  src/app/api/auth/signin/route.tsx
  src/app/signup/page.tsx
  src/app/testlogin/page.tsx
Labels: REFACTOR

#95 [✨feat]: 탐색하기 검색 구현
  src/app/search/page.tsx
Labels: FEAT

#98 [✨feat]: 회원 가입 API 반영
  src/app/signup/page.tsx
  src/app/testsignup/page.tsx
Labels: FEAT

#104 [✨feat]: walkthrough 링크 추가
  src/app/api/auth/signin/route.tsx
  src/app/signup/page.tsx
  src/app/testlogin/page.tsx
  src/app/walkthrough/page.tsx
Labels: FEAT

#102 [🎨style]: 전체 스타일 수정
  src/app/createstudy/page.tsx
  src/app/login/page.tsx
  src/app/manage-studyroom/page.tsx
  src/app/mypage/page.tsx
  src/app/signup/page.tsx
  src/app/testlogin/page.tsx
  src/components/common/Avatar.tsx
  src/components/common/CommonHeader.tsx
  src/components/common/Input.tsx
  src/components/common/NavHeader.tsx
  src/components/common/PendingProfileCard.tsx
Labels: STYLE

#105 [✨feat] 탐색하기-검색기능, 팀원찾기 구현
  public/images/ArrowCircleUpRight.svg
  src/app/manage-studyroom/page.tsx
  src/app/search/page.tsx
  src/app/studyroom/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/StudyroomCard.tsx
  src/components/common/TeamMemberCard.tsx
Labels: FEAT
